export const GET_COMPANY = "GET_COMPANY";
export const SET_SEARCH = "SET_SEARCH";
export const GET_COMPANY_FAILED = "GET_COMPANY_FAILED";
export const HANDLE_SEARCH_RESULT_CLICK = "HANDLE_SEARCH_RESULT_CLICK";
